config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: "auctions#index"

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post   '/bid',     to: 'bids#bid'
  resources :lots
  resources :users, except: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :lot
end

app/models/lot.rb
class Lot < ApplicationRecord
  paginates_per 12

  has_many :bids

  validates :name, presence: true, uniqueness: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :start_date_shoud_start_tomorrow, on: :create
  validate :end_date_shoud_be_in_future, on: :create
  validate :end_date_earlier_than_start_date, on: :create

  before_create :set_defaults

  scope :active, -> { where(status: 'active') }

  def active?
    self.status == 'active'
  end

  def finalize_bid(amount:, user_id:, bid_id:)
    self.current_highest_bid = amount
    self.current_highest_bidder = user_id
    self.status = 'closed' if amount >= self.price
    self.save!
    PaymentsWorker.perform_async(user_id, self.user_id, amount, bid_id, self.id) if amount >= self.price
  end

  def return_money_previous_bidder(current_user)
    if self.current_highest_bidder
      if self.current_highest_bidder == current_user.id
        current_user.add_money(self.current_highest_bid)
      else
        previous_bidder = User.find(self.current_highest_bidder)
        previous_bidder.add_money(self.current_highest_bid)
      end
    end
  end

  private

  def set_defaults
    self.current_highest_bid = 0
    self.end_date = self.end_date.end_of_day
    self.status = 'inactive'
  end

  def start_date_shoud_start_tomorrow
    if self.start_date.present? && self.start_date < DateTime.tomorrow.beginning_of_day
      errors.add(:start_date, "should start from tomorrow or further in future")
    end
  end

  def end_date_shoud_be_in_future
    if self.end_date.present? && self.end_date < (DateTime.now + 2.days).beginning_of_day
      errors.add(:start_date, "should start from tomorrow or further in future")
    end
  end

  def end_date_earlier_than_start_date
    if self.start_date.present? && self.end_date.present? && self.end_date < self.start_date
      errors.add(:end_date, "can't be earlier than Start Date")
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  has_many :payments, foreign_key: :user_id_from

  before_create :set_defaults

  def can_bid?(bid_amount:, lot:)
    return [false, 'This lot has been sold already'] if lot.status != 'active'
    return [false, "You can't bid on your lots"] if lot.user_id == self.id
    return [false, 'Your bid is lower than current highest bid'] if lot.current_highest_bid >= bid_amount
    return [false, 'Your bid is higher than your current balance'] if bid_amount > self.balance
    [true, nil]
  end

  def add_money(amount)
    self.balance += amount
    self.save!
  end

  def take_money(amount)
    self.balance -= amount
    self.save!
  end

  def bought_lots
    Lot.where(id: self.payments.pluck(:lot_id))
  end

  private

  def set_defaults
    self.balance = 0 if self.balance.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  def index
    @lots = Lot.active.order('created_at desc').page params[:page]
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def bid
    ActiveRecord::Base.transaction do
      lot = Lot.lock.find(params[:lot_id])
      result, message = current_user.can_bid?(bid_amount: params[:bid_amount].to_i, lot: lot)
      if result
        bid = Bid.create!(user_id: current_user.id, lot_id: lot.id, bid_amount: params[:bid_amount].to_i)
        lot.return_money_previous_bidder(current_user)
        current_user.take_money(params[:bid_amount].to_i)
        lot.finalize_bid(amount: params[:bid_amount].to_i, user_id: current_user.id, bid_id: bid.id)
        render json: { status: 200, message: 'Bidding was successful' }, status: 200
      else
        render json: { status: 401, message: message }, status: 401
      end
    end
  end
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  def index
    @lots = Lot.order('created_at desc').page params[:page]
  end

  def new
    @lot = Lot.new
  end

  def create
    @lot = Lot.new(lot_params)
    @lot.user_id = current_user.id
    if @lot.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @lot = Lot.find(params[:id])
  end

  private

  def lot_params
    params.require(:lot).permit(:name, :description, :start_date, :end_date, :price)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update_attributes(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :balance)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/auctions/index.html.erb
<% if @lots.present? %>
  <div class="card-columns">
    <% @lots.each do |lot| %>
      <div class="card" >
        <img src="https://picsum.photos/300/200?image=<%= rand(1000) %>" class="card-img-top" alt="Placeholder">
        <div class="card-body">
          <h5 class="card-title"><%= lot.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= number_to_currency(lot.price, unit: '€', precision: 0) %></h6>
          <p class="card-text ellipsis"><%= lot.description %></p>
          <%= link_to 'View Lot', lot_path(lot), class: 'card-link btn btn-primary'  %>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @lots %>
<% else %>
  <div class="card text-center">
    <div class="card-header">
      Oops...
    </div>
    <div class="card-body">
      <h5 class="card-title">There are no lots on this auction yet</h5>
      <p class="card-text">Try selling something by clicking the button below.</p>
      <%= link_to  'Add a Lot', new_lot_path, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuctionApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container main-content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lots/new.html.erb
<%= render partial: "shared/errors", locals: {object: @lot} %>
<%= form_for @lot, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= label_tag(:lot_name, "Name") %>
  <%= f.text_field :name, class: "form-control", required: true %>

  <%= label_tag(:lot_price, "Price") %>
  <%= f.number_field :price, class: "form-control", required: true %>

  <%= label_tag(:lot_description, "Description") %>
  <%= f.text_area :description, class: "form-control", rows: 3, required: true %>

  <%= label_tag(:lot_start_date, "Start Date") %>
  <%= f.date_field :start_date, class: "form-control", required: true %>

  <%= label_tag(:lot_end_date, "End Date") %>
  <%= f.date_field :end_date, class: "form-control", required: true %>
  <br><br>
  <%= f.submit "Create", class: "btn btn-primary mb-2" %>
<% end %>

app/views/lots/show.html.erb
<% if logged_in? %>
  <% if current_user.id == @lot.user_id %>
    <div class="alert alert-warning" role="alert">
      You can't bid on your own lots!
    </div>
  <% end %>
<% else %>
  <div class="alert alert-warning" role="alert">
    Please, Sign Up or Login to start bidding.
  </div>
<% end %>

<h1>
  <%= @lot.name %>
  <small class="text-muted" id="countdown-timer" data-end-date="<%= @lot.end_date %>" data-status="<%= @lot.status %>"></small>
</h1>
<h3>Buyout Price: <%= number_to_currency(@lot.price, unit: '€', precision: 0) %></h3>
<img src="https://picsum.photos/300/200?image=<%= rand(1000) %>" class="rounded float-left mr-5 mb-5" alt="Placeholder">
<p class="lead">
  <%= @lot.description %>
</p>
<% if logged_in? && @lot.active? && current_user.id != @lot.user_id %>
  <div class="input-group mb-3 w-25">
    <input type="text" class="form-control" placeholder="Your bid" aria-describedby="button-addon2" id="bid-amount" data-lot-id="<%= @lot.id %>" type="number">
    <div class="input-group-append">
      <button class="btn btn-success" type="button" id="button-addon2 make-a-bid">Bid</button>
    </div>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Bidder</th>
      <th scope="col">Amount</th>
      <th scope="col">Time</th>
    </tr>
  </thead>
  <tbody>
    <% @lot.bids.order('created_at desc').each do |bid| %>
      <tr>
        <td><%= "Bidder ##{bid.user_id}" %></td>
        <td><%= bid.bid_amount %></td>
        <td><%= bid.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_errors.html.erb
<% if object.errors.messages.present? %>
  <% object.errors.messages.each do |field, message| %>
    <% message.each do |m| %>
      <div class="alert alert-danger" role="alert">
        <%= field.to_s.humanize %> - <%= m %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Auction.io', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to  'Add a Lot', new_lot_path, class: 'nav-link btn btn-success', role: 'button' %>
        </li>
      <% end %>
    </ul>
    <% if logged_in? %>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.email %> <span class="badge badge-light"><%= number_to_currency(current_user.balance, unit: '€', precision: 0) %></span>
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to  'Top Up Balance', edit_user_path(current_user), class: 'dropdown-item' %>
          <%= link_to  'Logout', logout_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </div>
    <% else %>
      <%= link_to  'Sign Up', new_user_path, class: 'nav-link btn btn-success m-2', role: 'button' %>
      <%= link_to  'Login', login_path, class: 'nav-link btn btn-primary m-2', role: 'button' %>
    <% end %>
  </div>
</nav>

app/views/users/edit.html.erb
<%= form_for @user, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
  <%= label_tag(:user_balance, "Balance") %>
  <%= f.number_field :balance, class: "form-control", required: true %>

  <br><br>
  <%= f.submit "Top Up", class: "btn btn-primary mb-2" %>
<% end %>

app/views/users/new.html.erb
<%= render partial: "shared/errors", locals: {object: @user} %>
<%= form_for @user, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= label_tag(:user_email, "Email") %>
  <%= f.email_field :email, class: "form-control", required: true %>

  <%= label_tag(:user_password, "Password") %>
  <%= f.password_field :password, class: "form-control", required: true %>

  <%= label_tag(:user_password_confirmation, "Password Confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control", required: true %>

  <br><br>
  <%= f.submit "Create", class: "btn btn-primary mb-2" %>
<% end %>